version: '3'
services:
  docker-dynamic-dns:
      image: docker-dynamic-dns
      build:
          dockerfile : Dockerfile
          context: . 
      container_name: docker-dynamic-dns
      hostname: docker-dynamic-dns
      restart: unless-stopped
      environment:
        - UDP_PORT=53
        - UPSTREAM_DNS=8.8.8.8
        - DOMAIN=mydomain.home
        - ZONES_FILE=/config/sample-zones.txt
      networks:
          - net-docker-dynamic-dns
      ports:
          - 53:53/udp
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
          - /tmp/docker/docker-dynamic-dns/tmp:/tmp
          - /var/run/docker.sock:/var/run/docker.sock
          - ./app:/config:ro
      cap_add:
          - NET_BIND_SERVICE
      security_opt:
          - seccomp:unconfined

networks:
    net-docker-dynamic-dns:
        name: net-docker-dynamic-dns
        driver: bridge
